### ISSUE TITLE
yarn run serve 时报错

### ISSUE THREAD

**Issue by 526088078** [52admln/ts-vue-questionnaire#3]
Failed to compile with 1 errors                                                                       1:13:39 PM
 error  in ./src/utils/excel.ts

Module Error (from ./node_modules/eslint-loader/index.js):
error: 'cellValue' is never reassigned. Use 'const' instead (prefer-const) at src\utils\excel.ts:35:11:
  33 |         rowspan = parseInt(rowspanStr)
  34 |       }
> 35 |       let cellValue = cell.innerText
     |           ^
  36 |       // Skip ranges
  37 |       ranges.forEach(function(range) {
  38 |         if (R >= range.s.r && R <= range.e.r && outRow.length >= range.s.c && outRow.length <= range.e.c) {

error: Missing space before function parentheses (space-before-function-paren) at src\utils\excel.ts:37:30:
  35 |       let cellValue = cell.innerText
  36 |       // Skip ranges
> 37 |       ranges.forEach(function(range) {
     |                              ^
  38 |         if (R >= range.s.r && R <= range.e.r && outRow.length >= range.s.c && outRow.length <= range.e.c) {
  39 |           for (let i = 0; i <= range.e.c - range.s.c; ++i) outRow.push(null)
  40 |         }

error: 'result' is never reassigned. Use 'const' instead (prefer-const) at src\utils\excel.ts:201:9:
  199 |     }))
  200 |     // 以第一行为初始值
> 201 |     let result = colWidth[0]
      |         ^
  202 |     for (let i = 1; i < colWidth.length; i++) {
  203 |       for (let j = 0; j < colWidth[i].length; j++) {
  204 |         if (result[j]['wch'] < colWidth[i][j]['wch']) {

3 errors found.
3 errors potentially fixable with the `--fix` option.

**Comment by 52admln** [comment]
#4 已修复。
